### ISSUE TITLE
Problem with trackRoute

### ISSUE THREAD

**Issue by arnaudprioul** [TagCommander/ngx-tag-commander#12]
When we set trackRoute to True, we have an error 
**Cannot read property 'forEach' of undefined**

When i look code is see this 
`this.router.events.subscribe(function (_data) {
            if (_data instanceof RoutesRecognized && _this._trackRoutes) {
                if (_data.state.root.firstChild.data.tcInclude === undefined) {
                    /** @type {?} */
                    var data = _data.state.root.firstChild.data.tcInclude;
                    data.forEach(function (container) {
                        _this.reloadContainer(container["ids"], container["idc"], container["options"]);
                    });
                }
            }
        });`

i think have misstake, you mean if var is not undefined right ?

**Comment by arnaudprioul** [comment]
i use ngx-tag-commander 1.0.2

**Comment by RomainLK** [comment]
Fixed in 1.1.1 back in May.
