### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by gigeos** [TagCommander/ngx-tag-commander#2]
Hi,
I read in your README that you support AngularX 2+.
I would like to use your plugin for my ionic 3 project based on Angular 5. But I have the following error message:
`Object(...) is not a function`

I created two empty projects, one on Angular 5 and one on Angular 7. The first one didn't work when I imported `TagCommanderModule` in `AppModule.ts`, but the second one was okay. I suppose that is an issue with previous versions

Thank for your help

**Comment by TagCommander** [comment]
Hi, the spread operator is available after TypeScript 2.1. Can you check your version of TypeScript and if possible update it ? Thanks.

**Comment by gigeos** [comment]
Hi,

thank for your answer. My TypeScript's version is 2.4.2.
I think the problem is not spread operator but is line

**Comment by TagCommander** [comment]
It seems to be a problem with the typeScript version and the version of the other modules or Angular, that could not match, in other words, kind of a setup issue. Can you check that all your modules are in the right version regarding the version of typeScript ?
Thanks.

**Comment by gigeos** [comment]
I don't think this is the case because when I integrate the module into an Angular 5 empty project, it also has the error. In addition I see in your `package.json` dependancies Angular 7 and typescript  3.1.6, I am surprised that the versions are not lower if your module is Angular 2+ compatible

**Comment by MendozaMiguel** [comment]
Hello @gigeos ,
you can use this library in an empty project "npm i new-test-ngx", usually the problem should be solved with the new patch, but tagCommander should update their package on npm

**Comment by AlanRaz** [comment]
Hi,
Thanks.
But we can't take a dependency on unofficial library. @TagCommander, when do you plan to update your library with the fix ?
