### ISSUE TITLE
Any NPM Repo  ?

### ISSUE THREAD

**Issue by Meshredded** [TagCommander/ngx-tag-commander#5]
Hi,
Is there any NPM Repo for this library ?
Thanks.

**Comment by TagCommander** [comment]
Hi,
https://www.npmjs.com/package/ngx-tag-commander

**Comment by Meshredded** [comment]
Thank you,

So we are used to add the following scripts to our legacy apps in my company :
 - https://cdn.tagcommander.com/3431/tc_AG2RLaMondiale_1.js
 - https://cdn.tagcommander.com/3431/tc_AG2RLaMondiale_4.js
Now that we started using Angular as a frontend framework, should we add the previous scripts in addition to the ngx-tag-commander library ?

**Comment by Meshredded** [comment]
Thank you.
